# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/clion/bin/cmake/bin/cmake

# The command to remove a file.
RM = /opt/clion/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/crally/CRealm

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/crally/CRealm

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/clion/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/opt/clion/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/crally/CRealm/CMakeFiles /home/crally/CRealm/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/crally/CRealm/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CRealm

# Build rule for target.
CRealm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CRealm
.PHONY : CRealm

# fast build rule for target.
CRealm/fast:
	$(MAKE) -f CMakeFiles/CRealm.dir/build.make CMakeFiles/CRealm.dir/build
.PHONY : CRealm/fast

src/entity.o: src/entity.cpp.o

.PHONY : src/entity.o

# target to build an object file
src/entity.cpp.o:
	$(MAKE) -f CMakeFiles/CRealm.dir/build.make CMakeFiles/CRealm.dir/src/entity.cpp.o
.PHONY : src/entity.cpp.o

src/entity.i: src/entity.cpp.i

.PHONY : src/entity.i

# target to preprocess a source file
src/entity.cpp.i:
	$(MAKE) -f CMakeFiles/CRealm.dir/build.make CMakeFiles/CRealm.dir/src/entity.cpp.i
.PHONY : src/entity.cpp.i

src/entity.s: src/entity.cpp.s

.PHONY : src/entity.s

# target to generate assembly for a file
src/entity.cpp.s:
	$(MAKE) -f CMakeFiles/CRealm.dir/build.make CMakeFiles/CRealm.dir/src/entity.cpp.s
.PHONY : src/entity.cpp.s

src/game.o: src/game.cpp.o

.PHONY : src/game.o

# target to build an object file
src/game.cpp.o:
	$(MAKE) -f CMakeFiles/CRealm.dir/build.make CMakeFiles/CRealm.dir/src/game.cpp.o
.PHONY : src/game.cpp.o

src/game.i: src/game.cpp.i

.PHONY : src/game.i

# target to preprocess a source file
src/game.cpp.i:
	$(MAKE) -f CMakeFiles/CRealm.dir/build.make CMakeFiles/CRealm.dir/src/game.cpp.i
.PHONY : src/game.cpp.i

src/game.s: src/game.cpp.s

.PHONY : src/game.s

# target to generate assembly for a file
src/game.cpp.s:
	$(MAKE) -f CMakeFiles/CRealm.dir/build.make CMakeFiles/CRealm.dir/src/game.cpp.s
.PHONY : src/game.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/CRealm.dir/build.make CMakeFiles/CRealm.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/CRealm.dir/build.make CMakeFiles/CRealm.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/CRealm.dir/build.make CMakeFiles/CRealm.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/player_entity.o: src/player_entity.cpp.o

.PHONY : src/player_entity.o

# target to build an object file
src/player_entity.cpp.o:
	$(MAKE) -f CMakeFiles/CRealm.dir/build.make CMakeFiles/CRealm.dir/src/player_entity.cpp.o
.PHONY : src/player_entity.cpp.o

src/player_entity.i: src/player_entity.cpp.i

.PHONY : src/player_entity.i

# target to preprocess a source file
src/player_entity.cpp.i:
	$(MAKE) -f CMakeFiles/CRealm.dir/build.make CMakeFiles/CRealm.dir/src/player_entity.cpp.i
.PHONY : src/player_entity.cpp.i

src/player_entity.s: src/player_entity.cpp.s

.PHONY : src/player_entity.s

# target to generate assembly for a file
src/player_entity.cpp.s:
	$(MAKE) -f CMakeFiles/CRealm.dir/build.make CMakeFiles/CRealm.dir/src/player_entity.cpp.s
.PHONY : src/player_entity.cpp.s

src/scene_node.o: src/scene_node.cpp.o

.PHONY : src/scene_node.o

# target to build an object file
src/scene_node.cpp.o:
	$(MAKE) -f CMakeFiles/CRealm.dir/build.make CMakeFiles/CRealm.dir/src/scene_node.cpp.o
.PHONY : src/scene_node.cpp.o

src/scene_node.i: src/scene_node.cpp.i

.PHONY : src/scene_node.i

# target to preprocess a source file
src/scene_node.cpp.i:
	$(MAKE) -f CMakeFiles/CRealm.dir/build.make CMakeFiles/CRealm.dir/src/scene_node.cpp.i
.PHONY : src/scene_node.cpp.i

src/scene_node.s: src/scene_node.cpp.s

.PHONY : src/scene_node.s

# target to generate assembly for a file
src/scene_node.cpp.s:
	$(MAKE) -f CMakeFiles/CRealm.dir/build.make CMakeFiles/CRealm.dir/src/scene_node.cpp.s
.PHONY : src/scene_node.cpp.s

src/sprite_node.o: src/sprite_node.cpp.o

.PHONY : src/sprite_node.o

# target to build an object file
src/sprite_node.cpp.o:
	$(MAKE) -f CMakeFiles/CRealm.dir/build.make CMakeFiles/CRealm.dir/src/sprite_node.cpp.o
.PHONY : src/sprite_node.cpp.o

src/sprite_node.i: src/sprite_node.cpp.i

.PHONY : src/sprite_node.i

# target to preprocess a source file
src/sprite_node.cpp.i:
	$(MAKE) -f CMakeFiles/CRealm.dir/build.make CMakeFiles/CRealm.dir/src/sprite_node.cpp.i
.PHONY : src/sprite_node.cpp.i

src/sprite_node.s: src/sprite_node.cpp.s

.PHONY : src/sprite_node.s

# target to generate assembly for a file
src/sprite_node.cpp.s:
	$(MAKE) -f CMakeFiles/CRealm.dir/build.make CMakeFiles/CRealm.dir/src/sprite_node.cpp.s
.PHONY : src/sprite_node.cpp.s

src/texture_holder.o: src/texture_holder.cpp.o

.PHONY : src/texture_holder.o

# target to build an object file
src/texture_holder.cpp.o:
	$(MAKE) -f CMakeFiles/CRealm.dir/build.make CMakeFiles/CRealm.dir/src/texture_holder.cpp.o
.PHONY : src/texture_holder.cpp.o

src/texture_holder.i: src/texture_holder.cpp.i

.PHONY : src/texture_holder.i

# target to preprocess a source file
src/texture_holder.cpp.i:
	$(MAKE) -f CMakeFiles/CRealm.dir/build.make CMakeFiles/CRealm.dir/src/texture_holder.cpp.i
.PHONY : src/texture_holder.cpp.i

src/texture_holder.s: src/texture_holder.cpp.s

.PHONY : src/texture_holder.s

# target to generate assembly for a file
src/texture_holder.cpp.s:
	$(MAKE) -f CMakeFiles/CRealm.dir/build.make CMakeFiles/CRealm.dir/src/texture_holder.cpp.s
.PHONY : src/texture_holder.cpp.s

src/world.o: src/world.cpp.o

.PHONY : src/world.o

# target to build an object file
src/world.cpp.o:
	$(MAKE) -f CMakeFiles/CRealm.dir/build.make CMakeFiles/CRealm.dir/src/world.cpp.o
.PHONY : src/world.cpp.o

src/world.i: src/world.cpp.i

.PHONY : src/world.i

# target to preprocess a source file
src/world.cpp.i:
	$(MAKE) -f CMakeFiles/CRealm.dir/build.make CMakeFiles/CRealm.dir/src/world.cpp.i
.PHONY : src/world.cpp.i

src/world.s: src/world.cpp.s

.PHONY : src/world.s

# target to generate assembly for a file
src/world.cpp.s:
	$(MAKE) -f CMakeFiles/CRealm.dir/build.make CMakeFiles/CRealm.dir/src/world.cpp.s
.PHONY : src/world.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... CRealm"
	@echo "... src/entity.o"
	@echo "... src/entity.i"
	@echo "... src/entity.s"
	@echo "... src/game.o"
	@echo "... src/game.i"
	@echo "... src/game.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/player_entity.o"
	@echo "... src/player_entity.i"
	@echo "... src/player_entity.s"
	@echo "... src/scene_node.o"
	@echo "... src/scene_node.i"
	@echo "... src/scene_node.s"
	@echo "... src/sprite_node.o"
	@echo "... src/sprite_node.i"
	@echo "... src/sprite_node.s"
	@echo "... src/texture_holder.o"
	@echo "... src/texture_holder.i"
	@echo "... src/texture_holder.s"
	@echo "... src/world.o"
	@echo "... src/world.i"
	@echo "... src/world.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

